Tried adding some asnyc method but the problem is, the following (/home/charlessmith/csharp-development/CSharpPractice/ThreadJoiningE/Program.cs(14,39): error CS0120: An object reference is required for the non-static field, method, or property 'Program.GetApiResponse(string)' [/home/charlessmith/csharp-development/CSharpPractice/ThreadJoiningE/ThreadJoiningE.csproj])